<?php

namespace App\Http\Controllers;


use App\Models\ChartAnalysis;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Symfony\Component\HttpFoundation\Response;

class ChartAnalysisController extends Controller
{
    // AI graph analys

    public function analyze(Request $request) {
        // validate image upload
        $request->validate([
            'chart' => 'required|image|max:5120|mimes:jpeg,png,jpg,webp',
        ]);

        // claude api key check
        $apiKey = config('services.anthropic.key');

        if(!$apiKey){
            return response()->json([
                'message' => 'AI analyz service config error, need API key'
            ], Response::HTTP_INTERNAL_SERVER_ERROR);
        }

        try{
            $file = $request->file('chart');
            $mime = $file->getMimeType();

            //convert the image to base64 to send claude
            $base64 = base64_encode(file_get_contents($file->getRealPath()));

            // save the image to local disk public
            $path = $file->store('charts', 'public');
            $imageUrl= asset('storage/' . $path);
            $prompt = "You are a Senior Wall Street Technical Analyst and Chart Pattern Specialist.
Analyze the uploaded stock or crypto chart image in detail.
Identify support & resistance levels, visual candlestick or chart patterns, current trend direction, risk levels, and output a suggested trading strategy (entry, take-profit, stop-loss with rationale).
You MUST respond with a single, highly structured JSON object.
DO NOT wrap the response in markdown blocks like \`\`\`json or add any surrounding text. Return ONLY the raw JSON string starting with { and ending with }.
Use the following JSON schema:
{
  \"trend\": \"bullish\" | \"bearish\" | \"sideways\",
  \"trend_rationale\": \"Brief explanation of why this trend was identified\",
  \"support_levels\": [
    {\"price\": 120.50, \"strength\": \"strong\" | \"moderate\" | \"weak\"}
  ],
  \"resistance_levels\": [
    {\"price\": 130.00, \"strength\": \"strong\"}
  ],
  \"patterns\": [
    {\"name\": \"Double Bottom\", \"description\": \"Explanation of the pattern details.\"}
  ],
  \"trade_plan\": {
    \"entry\": 121.20,
    \"stop_loss\": 114.50,
    \"stop_loss_rationale\": \"Technical reasoning for the stop-loss level.\",
    \"take_profit\": 132.00
  },
  \"risk_level\": \"low\" | \"medium\" | \"high\",
  \"summary\": \"Detailed technical summary analyzing volume, moving averages, or indicators if visible.\",
  \"disclaimer\": \"This analysis is generated by AI and does not constitute financial advice.\"
}";

            // Claude 3.5 api request
            Log::info("Grafik Claude API'sine gönderiliyor...");
            $response = Http::withHeaders([
                'Content-Type'      => 'application/json',
                'x-api-key'         => $apiKey,
                'anthropic-version' => '2023-06-01',
            ])->timeout(60)->post(
                'https://api.anthropic.com/v1/messages',
                [
                    'model'      => 'claude-sonnet-4-6',
                    'max_tokens' => 4000,
                    'messages'   => [
                        [
                            'role'    => 'user',
                            'content' => [
                                [
                                    'type'   => 'image',
                                    'source' => [
                                        'type'       => 'base64',
                                        'media_type' => $mime,
                                        'data'       => $base64,
                                    ],
                                ],
                                [
                                    'type' => 'text',
                                    'text' => $prompt,
                                ],
                            ],
                        ],
                    ],
                ]
            );

            // response parse

            if($response->failed()){
                Log::error("Claude api error: " . $response->body());
                return response()->json([
                    'message' => 'Ai server error'
                ], Response::HTTP_BAD_GATEWAY);
            }

            $rawResult = $response->json();
            $textResponse = trim($rawResult['content'][0]['text'] ?? '');

            //Json clear if ``` delete

            if (str_starts_with($textResponse, '```json')) {
                $textResponse = substr($textResponse, 7);
            }
            if (str_ends_with($textResponse, '```')) {
                $textResponse = substr($textResponse, 0, -3);
            }
            $textResponse = trim($textResponse);
            $parsedJson = json_decode($textResponse, true);
            if (json_last_error() !== JSON_ERROR_NONE) {
                Log::error("JSON parse hatası: " . $textResponse);
                return response()->json([
                    'message' => 'AI output is failed.'
                ], Response::HTTP_UNPROCESSABLE_ENTITY);
            }

            //save response to db
            $analysis = ChartAnalysis::create([
                'user_id'    => $request->user()->id,
                'image_path' => $imageUrl,
                'result' => $parsedJson,
                'trend' => $parsedJson['trend'] ?? null,
                'risk_level' => $parsedJson['risk_level'] ?? null, 
            ]);

            return  response()->json([
                'success' => true,
                'data' => $analysis,
            ], Response::HTTP_CREATED);
        } catch (\Exception $e) {
            Log::error("Graph analysis error: " . $e->getMessage());
            return response()->json([
             'message' => 'An unexpected error occurred in the system.'
            ], Response::HTTP_INTERNAL_SERVER_ERROR);
        }

        
        
    }
    // liset past analysis fo the user
    public function history(Request $request){
            $analyses = ChartAnalysis::where('user_id', $request->user()->id)
                ->orderBy('created_at', 'desc')
                ->get();

            return response()->json([
                'success' => true,
                'data' => $analyses
            ]);
        }
    
}
