<?php

namespace App\Jobs;

use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use App\Models\ChartAnalysis;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;


class AnalyzeChartJob implements ShouldQueue
{
    use Queueable;

    public int $tries = 3;      // 3 kez dene, hep hata verirse failed say
        public int $timeout = 120; // bunlar otomatik okunur

    /**
     * Create a new job instance.
     */
    public function __construct(public int $analysisId)
    {
         
    }
        

    /**
     * Execute the job.
     */
    public function handle(): void
    {
        
        $analysis = ChartAnalysis::findOrFail($this->analysisId);

        $analysis->update(['status' => 'processing']);
        
        try {
            $apiKey = config('services.anthropic.key');

            $imageContent = Storage::disk(env('FILESYSTEM_DISK', 'public'))
                ->get(parse_url($analysis->image_path, PHP_URL_PATH));
            $base64 = base64_encode($imageContent);

            //mime type
            $extension = pathinfo($analysis->image_path, PATHINFO_EXTENSION);
            $mime = match ($extension) {
                'jpg', 'jpeg' => 'image/jpeg',
                'png' => 'image/png',
                'webp' => 'image/webp',
                default => 'image/jpeg'
            };
            $prompt = "You are a Senior Wall Street Technical Analyst and Chart Pattern Specialist.
Analyze the uploaded stock or crypto chart image in detail.
Identify support & resistance levels, visual candlestick or chart patterns, current trend direction, risk levels, and output a suggested trading strategy (entry, take-profit, stop-loss with rationale).
You MUST respond with a single, highly structured JSON object.
DO NOT wrap the response in markdown blocks like \`\`\`json or add any surrounding text. Return ONLY the raw JSON string starting with { and ending with }.
Use the following JSON schema:
{
  \"trend\": \"bullish\" | \"bearish\" | \"sideways\",
  \"trend_rationale\": \"Brief explanation of why this trend was identified\",
  \"support_levels\": [
    {\"price\": 120.50, \"strength\": \"strong\" | \"moderate\" | \"weak\"}
  ],
  \"resistance_levels\": [
    {\"price\": 130.00, \"strength\": \"strong\"}
  ],
  \"patterns\": [
    {\"name\": \"Double Bottom\", \"description\": \"Explanation of the pattern details.\"}
  ],
  \"trade_plan\": {
    \"entry\": 121.20,
    \"stop_loss\": 114.50,
    \"stop_loss_rationale\": \"Technical reasoning for the stop-loss level.\",
    \"take_profit\": 132.00
  },
  \"risk_level\": \"low\" | \"medium\" | \"high\",
  \"summary\": \"Detailed technical summary analyzing volume, moving averages, or indicators if visible.\",
  \"disclaimer\": \"This analysis is generated by AI and does not constitute financial advice.\"
}";

             // Claude 3.5 api request
            Log::info("Grafik Claude API'sine gönderiliyor...");
            $response = Http::withHeaders([
                'Content-Type' => 'application/json',
                'x-api-key' => $apiKey,
                'anthropic-version' => '2023-06-01',
            ])->timeout(90)->post('https://api.anthropic.com/v1/messages', [
                'model'      => 'claude-sonnet-4-6',
                'max_tokens' => 4000,
                'messages'   => [[
                    'role'    => 'user',
                    'content' => [
                        [
                            'type'   => 'image',
                            'source' => [
                                'type'       => 'base64',
                                'media_type' => $mime,
                                'data'       => $base64,
                            ],
                        ],
                        [
                            'type' => 'text',
                            'text' => $prompt,
                        ],
                    ],
                ]],
            ]);

            if($response->failed()){
                throw new \Exception("Claude API error: " . $response->body());
            }

            // 3. Response parse et
            $textResponse = trim($response->json()['content'][0]['text'] ?? '');

            if (str_starts_with($textResponse, '```json')) {
                $textResponse = substr($textResponse, 7);
            }
            if (str_ends_with($textResponse, '```')) {
                $textResponse = substr($textResponse, 0, -3);
            }
            $textResponse = trim($textResponse);

            $parsedJson = json_decode($textResponse, true);

            if (json_last_error() !== JSON_ERROR_NONE) {
                throw new \Exception('JSON parse error: ' . $textResponse);
            }

            $analysis->update([
                'status' => 'completed',
                'result' => $parsedJson,
                'trend' => $parsedJson['trend'] ?? null,
                'risk_level' => $parsedJson['risk_level'] ?? null,
            ]);

            Log::info("ChartAnalysis #{$this->analysisId} completed");

        } catch (\Throwable $th) {
            // 5. Hata → failed
            $analysis->update([
                'status'        => 'failed',
                'error_message' => $th->getMessage(),
            ]);

            Log::error("ChartAnalysis #{$this->analysisId} hata: " . $th->getMessage());

            throw $th; // Laravel'e de bildir → tries mekanizması çalışsın
        }

    }
}
